filebeat.inputs:
- type: log
  enabled: true
  paths:
    - /var/log/app/*.log
    - /var/log/app/**/*.log
  fields:
    service: portfolio-app
    environment: development
  fields_under_root: true
  multiline.pattern: '^\d{4}-\d{2}-\d{2}'
  multiline.negate: true
  multiline.match: after

- type: container
  enabled: true
  paths:
    - '/var/lib/docker/containers/*/*.log'
  processors:
    - add_docker_metadata:
        host: "unix:///var/run/docker.sock"

output.elasticsearch:
  hosts: ["elasticsearch:9200"]
  index: "portfolio-logs-%{+yyyy.MM.dd}"
  template.name: "portfolio-logs"
  template.pattern: "portfolio-logs-*"
  template.settings:
    index.number_of_shards: 1
    index.number_of_replicas: 0

processors:
  - add_host_metadata:
      when.not.contains.tags: forwarded
  - add_cloud_metadata: ~
  - add_docker_metadata: ~

logging.level: info
logging.to_files: true
logging.files:
  path: /var/log/filebeat
  name: filebeat
  keepfiles: 7
  permissions: 0644

setup.template.enabled: true
setup.template.settings:
  index.number_of_shards: 1
  index.codec: best_compression

setup.ilm.enabled: true
setup.ilm.rollover_alias: "portfolio-logs"
setup.ilm.pattern: "{now/d}-000001"