version: '3.8'

services:
  # DevContainer
  devcontainer:
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
    container_name: portfolio_devcontainer
    ports:
      - "3000:3000"  # Next.js
      - "8000:8000"  # FastAPI
    tty: true
    stdin_open: true
    volumes:
      - ..:/workspace:cached
      - /var/run/docker.sock:/var/run/docker.sock
    environment:
      - DATABASE_URL=mysql://portfolio_user:portfolio_pass@mysql:3306/portfolio_db
      - REDIS_URL=redis://redis:6379/0
      - ELASTICSEARCH_URL=http://elasticsearch:9200

  # MySQL データベース
  mysql:
    image: mysql:8.0
    container_name: portfolio_mysql
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: pass
      MYSQL_DATABASE: portfolio
      MYSQL_USER: portfolio_user
      MYSQL_PASSWORD: portfolio_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ../docker/mysql/init:/docker-entrypoint-initdb.d
      - ../docker/mysql/logs:/var/log/mysql

  # Elasticsearch
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.0
    container_name: portfolio_elasticsearch
    restart: unless-stopped
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - "ES_JAVA_OPTS=-Xms512m -Xmx1024m"
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
      - ../docker/elasticsearch/logs:/usr/share/elasticsearch/logs

  # Kibana
  kibana:
    image: docker.elastic.co/kibana/kibana:8.11.0
    container_name: portfolio_kibana
    restart: unless-stopped
    environment:
      - ELASTICSEARCH_HOSTS=http://elasticsearch:9200
      - xpack.security.enabled=false
    ports:
      - "5601:5601"
    volumes:
      - ../docker/kibana/logs:/usr/share/kibana/logs
    depends_on:
      - elasticsearch

  # Filebeat
  filebeat:
    image: docker.elastic.co/beats/filebeat:8.11.0
    container_name: portfolio_filebeat
    restart: unless-stopped
    user: root
    volumes:
      - ../docker/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
      - ../docker/filebeat/logs:/usr/share/filebeat/logs
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - /var/run/docker.sock:/var/run/docker.sock:ro
    depends_on:
      - elasticsearch
    command: filebeat -e -strict.perms=false

  # Redis (キャッシュ用)
  redis:
    image: redis:7-alpine
    container_name: portfolio_redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
      - ../docker/redis/logs:/var/log/redis

  # Nginx (リバースプロキシ)
  nginx:
    image: nginx:alpine
    container_name: portfolio_nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ../docker/nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ../docker/nginx/conf.d:/etc/nginx/conf.d:ro
      - ../docker/nginx/logs:/var/log/nginx
    depends_on:
      - mysql
      - redis

volumes:
  mysql_data:
    driver: local
  elasticsearch_data:
    driver: local
  redis_data:
    driver: local
